import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size: 30px;
        }
        h3{
          font-size: 20px;
        }
        `}
      </style>
      <Head>
        <title>Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src= '/sc.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan'>Techie's Blog</span>
        </h1>

        <p className={styles.description}>
          Space, Science and Tech
        </p>
<Image className ={styles.myImg} src="/homeimg.jpeg" alt="" width={570} height={380}/>
        <div className="blog">
          <h2>First Blog</h2>
          <div className="blogItem">
          <h3>Hi, my name is Bhanu Pratap</h3>
          <p>I am looking to get good practical experience in web development.</p>
          </div>
          <div className="blogItem">
          <h3>Hi, my name is Bhanu Pratap</h3>
          <p>I am looking to get good practical experience in web development.</p>
          </div>
          <div className="blogItem">
          <h3>Hi, my name is Bhanu Pratap</h3>
          <p>I am looking to get good practical experience in web development.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
