import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        .mySpan{
        color: red;
        }
        `}
      </style>
      <Head>
        <title>Tech Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src= '/sc.js' strategy='lazyOnload'></Script> */}
      <nav className={styles.mainNav}>
        <ul>
        <Link href={'/'}><li><a>Home</a></li></Link>
        <Link href={'/about'}><li><a>About</a></li></Link>
        <Link href={'/blog'}><li><a>Blog</a></li></Link>
        <Link href={'/contact'}><li><a>Contact</a></li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>
          <span className='mySpan'>Techie's Blog</span>
        </h1>

        <p className={styles.description}>
          Space, Science and Tech
        </p>

        <div className="blog">
          <h2>First Blog</h2>
          <div className="blogItem"></div>
          <h3>Hi, my name is Bhanu Pratap</h3>
          <p>I am looking to get good practical experience in web development.
          </p>
          <div className="blogItem"></div>
          <h3>Hi, my name is Bhanu Pratap</h3>
          <p>I am looking to get good practical experience in web development.
          </p>
          <div className="blogItem"></div>
          <h3>Hi, my name is Bhanu Pratap</h3>
          <p>I am looking to get good practical experience in web development.
          </p>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
